### ISSUE TITLE
source is missing

### ISSUE THREAD

**Issue by ysangkok** [kiniry/ESCJava2#1]
the links from kindsoftware says the source would be here. but it's not.

**Comment by cmavr8** [comment]
Indeed!
Was about to open the same issue

**Comment by kiniry** [comment]
We have been importing the SVN repo with version history, but GitHub rate-limits (to a limit) large repo imports.  I guess we'll just have to get rid of the history.  I'll look into pushing this next week.

**Comment by muratozkan** [comment]
Is this project dead?

**Comment by kiniry** [comment]
This project has been shut done and in maintenance mode for several years, as documented on the website.

**Comment by monperrus** [comment]
it would be really great to browse the source of ESCJava2 on Github (and facilitate evolution sharing with forks and PRs). 

What's the best version to consider among those listed at http://kindsoftware.com/products/opensource/archives/?

**Comment by kiniry** [comment]
I will still get around to pushing the SVN repo to GitHub someday.  For the moment, grab the last source release from the above link (ESCJava-2.0.5-04-11-08-source.tbz).

**Comment by ysangkok** [comment]
Thanks for the responses, I'll close this because having the history on Git is not so important to me any more.
